ADDRESSES = [
    "Rustaveli Avenue 1",
    "Agmashenebeli Avenue 5",
    "Tbilisi Street 10",
    "Chavchavadze Avenue 15",
    "Pushkin Street 20",
    "Freedom Square 25",
    "Rioni Street 30",
    "Kostava Street 35",
    "Marjanishvili Street 40",
    "Vera District 45",
    "David Agmashenebeli Avenue 50",
    "Tsereteli Avenue 55",
    "Rustaveli Avenue 60",
    "Saburtalo District 65",
    "Gamsakhurdia Avenue 70",
    "Vazha-Pshavela Avenue 75",
    "Tabidze Street 80",
    "Rike Park 85",
    "Melikishvili Street 90",
    "Baratashvili Street 95",
    "Dadiani Street 100",
    "Aghmashenebeli Alley 105",
    "Gorgasali Street 110",
    "Abashidze Street 115",
    "Vake District 120",
    "Gudiashvili Square 125",
    "Rustaveli Theatre 130",
    "Isani District 135",
    "Gorgiladze Street 140",
    "Marjanishvili Theatre 145",
    "Machabeli Street 150"
]
INITIIAL_THEMES = themes = [
    "Technology",
    "E-commerce",
    "Health and Wellness",
    "Financial Services",
    "Renewable Energy",
    "Sustainability",
    "Entertainment",
    "Media",
    "Education",
    "E-learning",
    "Food and Beverage",
    "Travel and Hospitality",
    "Manufacturing",
    "Engineering",
    "Automotive",
    "Aerospace",
    "Retail",
    "Fashion",
    "Real Estate",
    "Agriculture",
    "Biotechnology",
    "Pharmaceuticals",
    "Gaming",
    "Social Networking",
    "Transportation",
    "Logistics",
    "Artificial Intelligence",
    "Data Science",
    "Cryptocurrency",
    "Mobile Applications",
    "Cybersecurity",
    "Augmented Reality",
    "Virtual Reality",
    "Internet of Things (IoT)",
    "Robotics",
    "HealthTech",
    "FinTech",
    "SaaS (Software-as-a-Service)",
    "Cloud Computing",
    "Digital Marketing",
    "Advertising",
    "Market Research",
    "Sports and Fitness",
    "Music and Entertainment",
    "Home Automation",
    "Environmental Conservation",
    "Human Resources",
    "Event Management",
    "Social Impact",
    "Non-profit Organizations"
]
INITIAL_CITIES = ['თბილისი', 'ბათუმი', 'ქუთაისი', 'რუსთავი', 'გორი', 'ზუგდიდი', 'ფოთი', 'ხაშური', 'სამტრედია', 'სენაკი',
                  'ზესტაფონი', 'მარნეული', 'თელავი', 'ახალციხე', 'ქობულეთი', 'ოზურგეთი', 'კასპი', 'ჭიათურა', 'წყალტუბო',
                  'საგარეჯო']
COMPANIES = ['შპს სოკარ ჯორჯია პეტროლეუმი', 'შპს ტოიოტა კავკასია და ცენტრალური აზია', 'სს ვისოლ პეტროლიუმ ჯორჯია',
             'სს საქართველოს რკინიგზა', 'შპს სოკარ ჯორჯია გაზი', 'შპს რომპეტროლ საქართველო', 'შპს ჯორჯიან მანგანეზი',
             'შპს სან პეტროლიუმ ჯორჯია', 'სს საქართველოს ნავთობისა და გაზის კორპორაცია',
             'შპს სოკარ გაზ ექსპორტ-იმპორტი',
             'ბი-ფი ექსპლორეიშენ (კასპიის ზღვა) ლიმიტედის საქართველოს თბილისის ფილიალი', 'სს ენერგო - პრო ჯორჯია',
             'შპს პსპ ფარმა', 'შპს მაგთიკომი', 'შპს რუსთავის აზოტი', 'შპს ლუკოილ-ჯორჯია',
             'შპს ელიზი ჯგუფიშპს გაზ დისტრიბიუშენ კომპანი', 'შპს გაზ დისტრიბიუშენ კომპანი', 'სს თელასი', 'სს ჯი პი სი',
             'შპს ჯეი თი აი კავკასუს',
             'აიდიეს ბორჯომი საქართველო, შპს აიდიეს ბორჯომი ბევერიჯიზ კომპანის საქართველოს ფილიალი', 'შპს პსპ -აფთიაქი',
             'შპს ავერსი-ფარმა', 'შპს ჯეოსელი', 'შპს ყაზტრანსგაზ-თბილისი', 'შპს ომეგა-2', 'შპს ჰაიდელბერგცემენტ ჯორჯია',
             'შპს ავერსი-გეოფარმი', 'შპს ტოიოტა ცენტრი თბილისი', 'შპს ქართული კაზინოს ჯგუფი',
             'შპს საქართველოს გაზის ტრანსპორტირების კომპანია', 'შპს ჯორჯია ტრანზიტი',
             'სს ელექტროენერგეტიკული სისტემის კომერციული ოპერატორი', 'სს სილქნეტი', 'შპს ჯეოსთილი',
             'შპს რუსთავის ფოლადი', 'საქართველოს საერთაშორისო ენერგეტიკული კორპორაცია', 'შპს ეი-ბი-სი ფარმაცია',
             'შპს მობიტელი', 'სს ელიტ ელექტრონიქსი', 'შპს თეგეტა მოტორსი', 'სს RMG Copper', 'სს ლომისი',
             'ღია სააქციო საზოგადოება აზერიოლსერვისი-ს ფილიალი საქართველოში', 'შპს ალტა', 'შპს გუდვილი',
             'შპს კოკა-კოლა ბოთლერს ჯორჯია', 'შპს დიპლომატ ჯორჯია', 'შპს ფილიპ მორის საქართველო', 'შპს ჯეო ექსი',
             'შპს ოილი', 'შპს ი თი აი', 'სს სოკარ ჯორჯია გაზ დისტრიბუშენ', 'შპს აგარის შაქრის კომპანია',
             'შპს MAF HYPERMARKETS GEORGIA', 'შპს თ & რ დისტრიბუშენ', 'შპს ბი ენ ბი თრეიდი',
             'შპს ქართული სადისტრიბუციო-მარკეტინგული კომპანია',
             'შპს ერთობლივი საწარმოს ტოდინი ტაკენაკას ფილიალი საქართველოში', 'შპს ტექნო ბუმი', 'შპს ნიკორა ტრეიდი',
             'შპს მტკვარი ენერგეტიკა', 'შპს ჯორჯიან უოთერ ენდ ფაუერი', 'შპს ჯორჯიან ეარვეისი', 'შპს დაფნა',
             'სს კორპორაცია ფოთის საზღვაო ნავსადგური (ეი პი ემ ტერმინალს)', 'შპს ანაგი', 'შპს GEOBET',
             'შპს აგროსისტემები', 'შპს კორპორაცია სინოჰიდროს ფილიალი საქართველოში', 'შპს კავკასუს ონლაინი',
             'სს ჰიუნდაი ავტო საქართველო', 'შპს ტავ ურბან საქართველო', 'შპს Portal', 'შპს GDG',
             'შპს აიდიეს ბორჯომი თბილისი', 'სს ქართული ლუდის კომპანია', 'შპს აგრიკომი', 'შპს ევროტექნიკს ჯორჯია',
             'შპს ინტერ +', 'სს ფუდმარტი', 'შპს RMG Gold', 'შპს შარმ ტრეიდინგი', 'შპს ლიმონი 2009',
             'სს საქართველოს სახელმწიფო ელექტროსისტემა', 'შპს კია მოტორს ჯორჯია', 'შპს მეგაკო', 'შპს ფერი',
             'შპს ჯორჯიან პეტროლიუმი', 'შპს ბინული 1', 'შპს ჯი-ემ-პი', 'შპს ბი ემ სი გორგია',
             'აკკორდ-ის წარმომადგენლობა (ფილიალი) საქართველოში აკკორდ ჯორჯია', 'შპს იუ-ჯი-თი', 'შპს AGE BATUM',
             'შპს შავი ზღვის ტერმინალი', 'შპს საქაერონავიგაცია', 'შპს კავკასიის ავტოიმპორტი', 'შპს ჯი-თი მოტორს']
NAMES = ['Liam', 'Noah', 'Oliver', 'Elijah', 'William', 'James', 'Benjamin', 'Lucas', 'Henry', 'Alexander', 'Mason',
         'Michael', 'Ethan', 'Daniel', 'Jacob', 'Logan', 'Jackson', 'Levi', 'Sebastian', 'Mateo', 'Jack', 'Owen',
         'Theodore', 'Aiden', 'Samuel', 'Joseph', 'John', 'David', 'Wyatt', 'Matthew', 'Luke', 'Asher', 'Carter',
         'Julian', 'Grayson', 'Leo', 'Jayden', 'Gabriel', 'Isaac', 'Lincoln', 'Anthony', 'Hudson', 'Dylan', 'Ezra',
         'Thomas', 'Charles', 'Christopher', 'Jaxon', 'Maverick', 'Josiah', 'Isaiah', 'Andrew', 'Elias', 'Joshua',
         'Nathan', 'Caleb', 'Ryan', 'Adrian', 'Miles', 'Eli', 'Nolan', 'Christian', 'Aaron', 'Cameron', 'Ezekiel',
         'Colton', 'Luca', 'Landon', 'Hunter', 'Jonathan', 'Santiago', 'Axel', 'Easton', 'Cooper', 'Jeremiah', 'Angel',
         'Roman', 'Connor', 'Jameson', 'Robert', 'Greyson', 'Jordan', 'Ian', 'Carson', 'Jaxson', 'Leonardo', 'Nicholas',
         'Dominic', 'Austin', 'Everett', 'Brook', 'Xavier', 'Kai', 'Jose', 'Parker', 'Adam', 'Jace', 'Wesley', 'Kayden',
         'Silas']
